### ISSUE TITLE
Build fails on Swift 5.3 Docker image (Linux platform)

### ISSUE THREAD

**Issue by 417-72KI** [danger/swift#375]
```
$ docker run -it swift:5.3             
root@18d35d25f188:/# swift --version
Swift version 5.3 (swift-5.3-RELEASE)
Target: x86_64-unknown-linux-gnu
root@18d35d25f188:/# git clone --depth=1 -b master https://github.com/danger/danger-swift.git ~/danger-swift
...
root@18d35d25f188:/# make -C ~/danger-swift install
...
swift: /home/buildnode/jenkins/workspace/oss-swift-5.3-package-linux-ubuntu-18_04/llvm-project/llvm/lib/CodeGen/AsmPrinter/DwarfExpression.cpp:572: void llvm::DwarfExpression::addFragmentOffset(const llvm::DIExpression *): Assertion `FragmentOffset >= OffsetInBits && "overlapping or duplicate fragments"' failed.
Stack dump:
0.      Running pass 'Function Pass Manager' on module '/root/danger-swift/.build/x86_64-unknown-linux-gnu/release/Danger.build/BitBucketCloud.swift.o'.
1.      Running pass 'X86 Assembly Printer' on function '@"$s6Danger15BitBucketServerV11PullRequestV23__derived_struct_equalsySbAE_AEtFZTf4nnd_n"'
/usr/bin/swift[0x51f95a4]
/usr/bin/swift[0x51f719e]
/usr/bin/swift[0x51f987c]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x128a0)[0x7f20391348a0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7)[0x7f203779ff47]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x141)[0x7f20377a18b1]
/lib/x86_64-linux-gnu/libc.so.6(+0x3042a)[0x7f203779142a]
/lib/x86_64-linux-gnu/libc.so.6(+0x304a2)[0x7f20377914a2]
/usr/bin/swift[0x23e818a]
/usr/bin/swift[0x2431088]
/usr/bin/swift[0x242f51a]
/usr/bin/swift[0x242ed54]
/usr/bin/swift[0x24301af]
/usr/bin/swift[0x242ed97]
/usr/bin/swift[0x24301af]
/usr/bin/swift[0x2431ef8]
/usr/bin/swift[0x23d0970]
/usr/bin/swift[0x24285f4]
/usr/bin/swift[0x23ab3ac]
/usr/bin/swift[0x1acc306]
/usr/bin/swift[0x2fcb8ea]
/usr/bin/swift[0x505ccee]
/usr/bin/swift[0x505d063]
/usr/bin/swift[0x505d69f]
/usr/bin/swift[0x8963dd]
/usr/bin/swift[0x89d0bc]
/usr/bin/swift[0x89ce76]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xbd6df)[0x7f2037e276df]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76db)[0x7f20391296db]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f2037882a3f]

Makefile:31: recipe for target 'build' failed
make: *** [build] Error 1
make: Leaving directory '/root/danger-swift'
```

## Note
Build on macOS Catalina has succeeded.

**Comment by f-meloni** [comment]
I looked on Google to see if I could find something useful, and to me this looks like an llvm bug

**Comment by f-meloni** [comment]
It might be possible that this was fixed on Swift 5.3.1 https://travis-ci.org/github/danger/swift/jobs/743517341#L246

**Comment by 417-72KI** [comment]
I tried at official [swift:5.3.1 image](https://hub.docker.com/_/swift), but it still occurs. 😫

When I use `swift build` it has succeeded, but using `swift build -c release` occurred this problem. 🧐

**Comment by f-meloni** [comment]
😥 It might be that we will have to build with without -c on Linux 5.3.1, not really happy of that, but better than crashing I suppose

**Comment by tibo** [comment]
I'm experiencing this issue as well when running on docker based on the `swift:5.3.2-focal` image.

**Comment by f-meloni** [comment]
@tibo try to build danger with 

```swift
swift package clean
swift build --disable-sandbox
```

Instead of using the one with `-c release` that is on the Makefile in the root folder.
It might be a workaround for the issue swift 5.3 introduced on Linux

**Comment by tibo** [comment]
yes thanks! 
I've read the previous comment and I've made my own Makefile. 
following this issue for a better solution 👀.

**Comment by mathaeus** [comment]
We're having the same issue.

I tried forking and adapting the `Makefile` as suggested (i.e. removing the `-c release` part) but that also gives me an error 😞 

```
cp: cannot stat '.build/release/danger-swift': No such file or directory
make: *** [install] Error 1
Makefile:25: recipe for target 'install' failed
```

@tibo how did you solve it? Are you using a Dockerfile?

**Comment by 417-72KI** [comment]
@mathaeus 
try to change [Makefile:L7](https://github.com/freeletics/danger-swift/commit/ce03764fd2e9dba1b42939ab4cf842cfb344a716#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52L7) to

```makefile
BUILD_PATH = .build/debug/$(TOOL_NAME)
```

**Comment by mathaeus** [comment]
Thx @417-72KI, that was indeed missing. Also 
[Makefile:L10](https://github.com/freeletics/danger-swift/commit/ce03764fd2e9dba1b42939ab4cf842cfb344a716#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R10) though!

**Comment by tibo** [comment]
you will also need to target the proper files/paths for the install phase

**Comment by mathaeus** [comment]
@tibo not sure if I understand. I ended up using the following git patch, and that seems to do it:

```
diff --git a/Makefile b/Makefile
index fcf09af..fcc887a 100644
--- a/Makefile
+++ b/Makefile
@@ -4,10 +4,10 @@ VERSION = 3.7.1
 
 PREFIX = /usr/local
 INSTALL_PATH = $(PREFIX)/bin/$(TOOL_NAME)
-BUILD_PATH = .build/release/$(TOOL_NAME)
+BUILD_PATH = .build/debug/$(TOOL_NAME)
 LIB_INSTALL_PATH = $(PREFIX)/lib/danger
 
-SWIFT_LIB_FILES = .build/release/libDanger.* .build/release/Danger.swiftdoc .build/release/Danger.swiftmodule .build/release/OctoKit.swiftdoc .build/release/OctoKit.swiftmodule .build/release/RequestKit.swiftdoc .build/release/RequestKit.swiftmodule .build/release/Logger.swiftdoc .build/release/Logger.swiftmodule .build/release/DangerShellExecutor.swiftdoc .build/release/DangerShellExecutor.swiftmodule
+SWIFT_LIB_FILES = .build/debug/libDanger.* .build/debug/Danger.swiftdoc .build/debug/Danger.swiftmodule .build/debug/OctoKit.swiftdoc .build/debug/OctoKit.swiftmodule .build/debug/RequestKit.swiftdoc .build/debug/RequestKit.swiftmodule .build/debug/Logger.swiftdoc .build/debug/Logger.swiftmodule .build/debug/DangerShellExecutor.swiftdoc .build/debug/DangerShellExecutor.swiftmodule
 
 docs: 
 	swift run swift-doc generate Sources/Danger --module-name Danger --output Documentation/reference --format html
@@ -29,7 +29,7 @@ install: build
 
 build:
 	swift package clean
-	swift build --disable-sandbox -c release
+	swift build --disable-sandbox
 
 uninstall:
 	rm -f $(INSTALL_PATH)
```

**Comment by f-meloni** [comment]
This should now be fixed by https://github.com/danger/swift/pulls?q=is%3Apr+is%3Aclosed

**Comment by f-meloni** [comment]
Closing, if you still have issues with Swift 5.3 and docker please re open it
